### ISSUE TITLE
model_gene_based.run_model_kfold error

### ISSUE THREAD

**Issue by fguntoro** [AmirHoseinSafari/LRCN-drug-resistance#2]
Hi Amir,

Thanks for your pointers in your previous emails. I was able to run ML_methods.model_run fine.

Just bringing up an error I received from model_gene_based.run_model_kfold (commit: 5db94335aec7fcdae81511994ff7bac350981703):

Debug error message from model_gene_based.py line 448
> history = model.fit(

**Exception has occurred: ValueError
in user code:

    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    c:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\models\model_gene_based.py:16 masked_loss_function  *
        return K.binary_crossentropy(y_true * mask, y_pred * mask)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\ops\math_ops.py:1141 binary_op_wrapper
        raise e
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\ops\math_ops.py:1125 binary_op_wrapper
        return func(x, y, name=name)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\ops\math_ops.py:1457 _mul_dispatch
        return multiply(x, y, name=name)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\ops\math_ops.py:509 multiply
        return gen_math_ops.mul(x, y, name)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\ops\gen_math_ops.py:6174 mul
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\framework\op_def_library.py:742 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\framework\func_graph.py:591 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\framework\ops.py:3477 _create_op_internal
        ret = Operation(
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\framework\ops.py:1974 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\framework\ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 20 and 12 for '{{node masked_loss_function/mul_1}} = Mul[T=DT_FLOAT](masked_loss_function/Cast, masked_loss_function/Cast_1)' with input shapes: [?,200,20], [?,12].

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "C:\Users\Fernando\AppData\Local\Temp\tmpjhdi3nmf.py", line 14, in tf__masked_loss_function
    retval_ = ag__.converted_call(ag__.ld(K).binary_crossentropy, ((ag__.ld(y_true) * ag__.ld(mask)), (ag__.ld(y_pred) * ag__.ld(mask))), None, fscope)

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "C:\Users\Fernando\AppData\Local\Temp\tmp2387br7t.py", line 16, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)

During handling of the above exception, another exception occurred:

  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\models\model_gene_based.py", line 448, in model_shuffle_index_0
    history = model.fit(
  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\models\model_gene_based.py", line 524, in run_model_kfold
    score1, score_all = model_shuffle_index_0(FrameSize, X, X_train, X_test, y_train, y_test, epoch, earlyStopping, "24J_" + str(i), index)
  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\pipe_line_gene.py", line 23, in train
    model_gene_based.run_model_kfold(df_train,labels,epochs)
  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\pipe_line_gene.py", line 71, in <module>
    train()**

**Comment by AmirHoseinSafari** [comment]
Hi Fernando,

Thanks for your message.

It's a bit weird error message. Please let me know if it still occurs after fixing the packages' version.

By the way, this method was not used in any results of the paper, so probably I will delete it in the final version of the code.

Sincerely,
Amir
