### ISSUE TITLE
model_gene_based.run_model error

### ISSUE THREAD

**Issue by fguntoro** [AmirHoseinSafari/LRCN-drug-resistance#3]
Hi Amir,

A debugging error from model_gene_based.run_model (see below)
I wonder if there is a quick fix for this?

Regards,
Fernando

**Exception has occurred: ValueError
in user code:

    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\sequential.py:386 call
        outputs = layer(inputs, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\layers\core.py:216 call
        output = tf_utils.smart_cond(training,
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py:64 smart_cond
        return smart_module.smart_cond(
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\framework\smart_cond.py:54 smart_cond
        return true_fn()
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\keras\layers\core.py:210 dropped_inputs
        return nn.dropout(
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\util\deprecation.py:507 new_func
        return func(*args, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\ops\nn_ops.py:4942 dropout
        return dropout_v2(x, rate, noise_shape=noise_shape, seed=seed, name=name)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Users\Fernando\anaconda3\envs\Project2 ML-Pred\lib\site-packages\tensorflow\python\ops\nn_ops.py:5027 dropout_v2
        raise ValueError("x has to be a floating point tensor since it's going "

    ValueError: x has to be a floating point tensor since it's going to be scaled. Got a <dtype: 'int32'> tensor instead.
  File "C:\Users\Fernando\AppData\Local\Temp\tmpo0631vl5.py", line 16, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)

During handling of the above exception, another exception occurred:

  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\models\model_gene_based.py", line 220, in model_CNN_LSTM_time
    history = model.fit(
  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\models\model_gene_based.py", line 550, in run_model
    model_CNN_LSTM_time(FrameSize, X, X_train, X_test, y_train, y_test, epoch, earlyStopping, "gene_10_" + str(i))
  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\pipe_line_gene.py", line 18, in train
    model_gene_based.run_model(df_train, labels, epochs)
  File "C:\Users\Fernando\Documents\MRes Biomedical Research\Project 2\Investigation\LRCN drug prediction\LRCN-drug-resistance\pipe_line_gene.py", line 71, in <module>
    train()**

**Comment by AmirHoseinSafari** [comment]
Hi Fernando,

Thanks for your message.

Probably, the problem is with the Keras and Tensorflow versions. I will list the versions that are compatible with the code and please make sure that you are using the same versions.

```
tensorflow                2.2.0             
tensorflow-base           2.2.0            
tensorflow-estimator      2.2.0               
tensorflow-gpu            2.2.0               

keras-base                2.3.1                      
keras-gpu                 2.3.1                        
```

Please let me know if it still doesn't work.

Sincerely,
Amir
